services:
  - type: web
    name: phishing-detection-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://phishing-detection-response-system.vercel.app
      - key: PORT
        value: 10000
