services:
  - type: WebService
    name: phishing-detection-api
    env: Node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://phishing-detection-response-system.vercel.app
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /api/health
